export const mapData = [{
    nodes: [
        { id: "78계단 3", x: 250, y: 460, },
        { id: "지곡연못 2", x: 100, y: 390 },
        { id: "지곡연못 3", x: 150, y: 410, },
        { id: "78계단 2", x: 250, y: 410 },
        { id: "대학원아파트 2", x: 350, y: 410, },
        { id: "대학원아파트 3", x: 400, y: 390, },
        { id: "지곡연못 1", x: 100, y: 340 },
        { id: "78계단 1", x: 250, y: 360 },
        { id: "대학원아파트 1", x: 350, y: 360 },
        { id: "지곡회관 3", x: 100, y: 290 },
        { id: "지곡회관 2", x: 150, y: 310, },
        { id: "지곡회관 1", x: 200, y: 290 },
        { id: "해동78타워 5", x: 250, y: 310, },
        { id: "교수아파트 1", x: 300, y: 290 },
        { id: "교수아파트 2", x: 350, y: 310 },
        { id: "교수아파트 3", x: 400, y: 290 },
        { id: "해동78타워 4", x: 250, y: 260 },
        { id: "해동78타워 3", x: 250, y: 210, },
        { id: "RC 20동 1", x: 300, y: 190 },
        { id: "RC 20동 2", x: 350, y: 210, },
        { id: "RC 20동 3", x: 400, y: 190 },
        { id: "해동78타워 2", x: 250, y: 160 },
        { id: "해동78타워 1", x: 250, y: 110, },
        { id: "RC 21동 3", x: 300, y: 90 },
        { id: "RC 21동 2", x: 350, y: 110, },
        { id: "RC 21동 1", x: 400, y: 90, },
    ],
    links: [
        { source: "78계단 3", target: "78계단 2" },
        { source: "지곡연못 2", target: "지곡연못 3" },
        { source: "지곡연못 2", target: "지곡연못 1" },
        { source: "지곡연못 3", target: "지곡연못 2" },
        { source: "78계단 2", target: "78계단 3" },
        { source: "78계단 2", target: "78계단 1" },
        { source: "대학원아파트 2", target: "대학원아파트 3" },
        { source: "대학원아파트 2", target: "대학원아파트 1" },
        { source: "대학원아파트 3", target: "대학원아파트 2" },
        { source: "지곡연못 1", target: "지곡연못 2" },
        { source: "지곡연못 1", target: "지곡회관 3" },
        { source: "78계단 1", target: "78계단 2" },
        { source: "78계단 1", target: "해동78타워 5" },
        { source: "대학원아파트 1", target: "대학원아파트 2" },
        { source: "대학원아파트 1", target: "교수아파트 2" },
        { source: "지곡회관 3", target: "지곡회관 2" },
        { source: "지곡회관 3", target: "지곡연못 1" },
        { source: "지곡회관 2", target: "지곡회관 1" },
        { source: "지곡회관 2", target: "지곡회관 3" },
        { source: "지곡회관 1", target: "해동78타워 5" },
        { source: "지곡회관 1", target: "지곡회관 2" },
        { source: "해동78타워 5", target: "교수아파트 1" },
        { source: "해동78타워 5", target: "지곡회관 1" },
        { source: "해동78타워 5", target: "78계단 1" },
        { source: "해동78타워 5", target: "해동78타워 4" },
        { source: "교수아파트 1", target: "교수아파트 2" },
        { source: "교수아파트 1", target: "해동78타워 5" },
        { source: "교수아파트 2", target: "교수아파트 3" },
        { source: "교수아파트 2", target: "교수아파트 1" },
        { source: "교수아파트 2", target: "대학원아파트 1" },
        { source: "교수아파트 3", target: "교수아파트 2" },
        { source: "해동78타워 4", target: "해동78타워 5" },
        { source: "해동78타워 4", target: "해동78타워 3" },
        { source: "해동78타워 3", target: "RC 20동 1" },
        { source: "해동78타워 3", target: "해동78타워 4" },
        { source: "해동78타워 3", target: "해동78타워 2" },
        { source: "RC 20동 1", target: "RC 20동 2" },
        { source: "RC 20동 1", target: "해동78타워 3" },
        { source: "RC 20동 2", target: "RC 20동 3" },
        { source: "RC 20동 2", target: "RC 20동 1" },
        { source: "RC 20동 3", target: "RC 20동 2" },
        { source: "해동78타워 2", target: "해동78타워 3" },
        { source: "해동78타워 2", target: "해동78타워 1" },
        { source: "해동78타워 1", target: "RC 21동 3" },
        { source: "해동78타워 1", target: "해동78타워 2" },
        { source: "RC 21동 3", target: "RC 21동 2" },
        { source: "RC 21동 3", target: "해동78타워 1" },
        { source: "RC 21동 2", target: "RC 21동 1" },
        { source: "RC 21동 2", target: "RC 21동 3" },
        { source: "RC 21동 1", target: "RC 21동 2" },
    ],
},{
    nodes: [
        { id: "철강대학원 3", x: 400, y: 440, },
        { id: "체인지업그라운드 3", x: 100, y: 390, },
        { id: "체인지업그라운드 2", x: 150, y: 410, },
        { id: "생명공학연구센터 2", x: 250, y: 410 },
        { id: "생명공학연구센터 3", x: 300, y: 390, },
        { id: "철강대학원 2", x: 400, y: 390, },
        { id: "체인지업그라운드 1", x: 150, y: 360 },
        { id: "생명공학연구센터 1", x: 250, y: 360 },
        { id: "철강대학원 1", x: 400, y: 340 },
        { id: "박태준학술정보관 3", x: 100, y: 290 },
        { id: "박태준학술정보관 2", x: 150, y: 310 },
        { id: "박태준학술정보관 1", x: 200, y: 290 },
        { id: "동문 1", x: 250, y: 310, },
        { id: "한국로봇융합연구원 1", x: 300, y: 290 },
        { id: "한국로봇융합연구원 2", x: 350, y: 310 },
        { id: "한국로봇융합연구원 3", x: 400, y: 290 },
        { id: "동문 2", x: 250, y: 260 },
        { id: "C5 2", x: 150, y: 210 },
        { id: "C5 1", x: 200, y: 190 },
        { id: "동문 3", x: 250, y: 210 },
        { id: "C5 3", x: 150, y: 160 },
        { id: "동문 4", x: 250, y: 160 },
        { id: "지곡연구동 3", x: 350, y: 160, },
        { id: "동문 5", x: 250, y: 110 },
        { id: "지곡연구동 1", x: 300, y: 90 },
        { id: "지곡연구동 2", x: 350, y: 110, },
    ],
    links: [
        { source: "철강대학원 3", target: "철강대학원 2" },
        { source: "체인지업그라운드 3", target: "체인지업그라운드 2" },
        { source: "체인지업그라운드 2", target: "체인지업그라운드 3" },
        { source: "체인지업그라운드 2", target: "체인지업그라운드 1" },
        { source: "생명공학연구센터 2", target: "생명공학연구센터 3" },
        { source: "생명공학연구센터 2", target: "생명공학연구센터 1" },
        { source: "생명공학연구센터 3", target: "생명공학연구센터 2" },
        { source: "철강대학원 2", target: "철강대학원 3" },
        { source: "철강대학원 2", target: "철강대학원 1" },
        { source: "체인지업그라운드 1", target: "체인지업그라운드 2" },
        { source: "체인지업그라운드 1", target: "박태준학술정보관 2" },
        { source: "생명공학연구센터 1", target: "생명공학연구센터 2" },
        { source: "생명공학연구센터 1", target: "동문 1" },
        { source: "철강대학원 1", target: "철강대학원 2" },
        { source: "철강대학원 1", target: "한국로봇융합연구원 3" },
        { source: "박태준학술정보관 3", target: "박태준학술정보관 2" },
        { source: "박태준학술정보관 2", target: "박태준학술정보관 1" },
        { source: "박태준학술정보관 2", target: "박태준학술정보관 3" },
        { source: "박태준학술정보관 2", target: "체인지업그라운드 1" },
        { source: "박태준학술정보관 1", target: "동문 1" },
        { source: "박태준학술정보관 1", target: "박태준학술정보관 2" },
        { source: "동문 1", target: "한국로봇융합연구원 1" },
        { source: "동문 1", target: "박태준학술정보관 1" },
        { source: "동문 1", target: "생명공학연구센터 1" },
        { source: "동문 1", target: "동문 2" },
        { source: "한국로봇융합연구원 1", target: "한국로봇융합연구원 2" },
        { source: "한국로봇융합연구원 1", target: "동문 1" },
        { source: "한국로봇융합연구원 2", target: "한국로봇융합연구원 3" },
        { source: "한국로봇융합연구원 2", target: "한국로봇융합연구원 1" },
        { source: "한국로봇융합연구원 3", target: "한국로봇융합연구원 2" },
        { source: "한국로봇융합연구원 3", target: "철강대학원 1" },
        { source: "동문 2", target: "동문 1" },
        { source: "동문 2", target: "동문 3" },
        { source: "C5 2", target: "C5 1" },
        { source: "C5 2", target: "C5 3" },
        { source: "C5 1", target: "동문 3" },
        { source: "C5 1", target: "C5 2" },
        { source: "동문 3", target: "C5 1" },
        { source: "동문 3", target: "동문 2" },
        { source: "동문 3", target: "동문 4" },
        { source: "C5 3", target: "C5 2" },
        { source: "동문 4", target: "동문 3" },
        { source: "동문 4", target: "동문 5" },
        { source: "지곡연구동 3", target: "지곡연구동 2" },
        { source: "동문 5", target: "지곡연구동 1" },
        { source: "동문 5", target: "동문 4" },
        { source: "지곡연구동 1", target: "지곡연구동 2" },
        { source: "지곡연구동 1", target: "동문 5" },
        { source: "지곡연구동 2", target: "지곡연구동 1" },
        { source: "지곡연구동 2", target: "지곡연구동 3" },
    ],
},{
    nodes: [
        { id: "수리과학관 1", x: 100, y: 440 },
        { id: "수리과학관 2", x: 150, y: 460, },
        { id: "제1공학관 2", x: 350, y: 460, },
        { id: "제1공학관 1", x: 400, y: 440 },
        { id: "대강당 2", x: 100, y: 390, },
        { id: "무은재기념관 2", x: 400, y: 390, },
        { id: "대강당 1", x: 100, y: 340 },
        { id: "무은재기념관 1", x: 400, y: 340 },
        { id: "제3공학관 2", x: 100, y: 290 },
        { id: "제3공학관 1", x: 150, y: 310 },
        { id: "제2공학관 1", x: 350, y: 310 },
        { id: "제2공학관 2", x: 400, y: 290 },
        { id: "제5공학관 2", x: 150, y: 260 },
        { id: "제5공학관 1", x: 200, y: 240 },
        { id: "학생회관 1", x: 250, y: 260, },
        { id: "제4공학관 1", x: 300, y: 240 },
        { id: "제4공학관 2", x: 350, y: 260 },
        { id: "학생회관 2", x: 250, y: 210 },
        { id: "학생회관 3", x: 250, y: 160 },
        { id: "학생회관 4", x: 250, y: 110 },
        { id: "국제관 1", x: 300, y: 90 },
        { id: "국제관 2", x: 350, y: 110, },
        { id: "국제관 3", x: 400, y: 90 },
        { id: "대운동장 3", x: 150, y: 60, },
        { id: "대운동장 2", x: 200, y: 40, },
        { id: "대운동장 1", x: 250, y: 60 },
    ],
    links: [
        { source: "수리과학관 1", target: "수리과학관 2" },
        { source: "수리과학관 1", target: "대강당 2" },
        { source: "수리과학관 2", target: "수리과학관 1" },
        { source: "제1공학관 2", target: "제1공학관 1" },
        { source: "제1공학관 1", target: "제1공학관 2" },
        { source: "제1공학관 1", target: "무은재기념관 2" },
        { source: "대강당 2", target: "수리과학관 1" },
        { source: "대강당 2", target: "대강당 1" },
        { source: "무은재기념관 2", target: "제1공학관 1" },
        { source: "무은재기념관 2", target: "무은재기념관 1" },
        { source: "대강당 1", target: "대강당 2" },
        { source: "대강당 1", target: "제3공학관 2" },
        { source: "무은재기념관 1", target: "무은재기념관 2" },
        { source: "무은재기념관 1", target: "제2공학관 2" },
        { source: "제3공학관 2", target: "제3공학관 1" },
        { source: "제3공학관 2", target: "대강당 1" },
        { source: "제3공학관 1", target: "제3공학관 2" },
        { source: "제3공학관 1", target: "제5공학관 2" },
        { source: "제2공학관 1", target: "제2공학관 2" },
        { source: "제2공학관 1", target: "제4공학관 2" },
        { source: "제2공학관 2", target: "제2공학관 1" },
        { source: "제2공학관 2", target: "무은재기념관 1" },
        { source: "제5공학관 2", target: "제5공학관 1" },
        { source: "제5공학관 2", target: "제3공학관 1" },
        { source: "제5공학관 1", target: "학생회관 1" },
        { source: "제5공학관 1", target: "제5공학관 2" },
        { source: "학생회관 1", target: "제4공학관 1" },
        { source: "학생회관 1", target: "제5공학관 1" },
        { source: "학생회관 1", target: "학생회관 2" },
        { source: "제4공학관 1", target: "제4공학관 2" },
        { source: "제4공학관 1", target: "학생회관 1" },
        { source: "제4공학관 2", target: "제4공학관 1" },
        { source: "제4공학관 2", target: "제2공학관 1" },
        { source: "학생회관 2", target: "학생회관 1" },
        { source: "학생회관 2", target: "학생회관 3" },
        { source: "학생회관 3", target: "학생회관 2" },
        { source: "학생회관 3", target: "학생회관 4" },
        { source: "학생회관 4", target: "국제관 1" },
        { source: "학생회관 4", target: "학생회관 3" },
        { source: "학생회관 4", target: "대운동장 1" },
        { source: "국제관 1", target: "국제관 2" },
        { source: "국제관 1", target: "학생회관 4" },
        { source: "국제관 2", target: "국제관 3" },
        { source: "국제관 2", target: "국제관 1" },
        { source: "국제관 3", target: "국제관 2" },
        { source: "대운동장 3", target: "대운동장 2" },
        { source: "대운동장 2", target: "대운동장 1" },
        { source: "대운동장 2", target: "대운동장 3" },
        { source: "대운동장 1", target: "대운동장 2" },
        { source: "대운동장 1", target: "학생회관 4" },
    ],
},{
    nodes: [
        { id: "RIST 4", x: 200, y: 440 },
        { id: "RIST 3", x: 250, y: 460, },
        { id: "RIST 5", x: 300, y: 440, },
        { id: "노벨동산 4", x:  50, y: 410, },
        { id: "노벨동산 2", x: 150, y: 410 },
        { id: "RIST 2", x: 250, y: 410 },
        { id: "노벨동산 3", x:  50, y: 360, },
        { id: "노벨동산 1", x: 150, y: 360 },
        { id: "RIST 1", x: 250, y: 360 },
        { id: "대학본관 4", x: 400, y: 340, },
        { id: "인공지능연구원 4", x:  50, y: 310 },
        { id: "인공지능연구원 3", x: 100, y: 290 },
        { id: "인공지능연구원 2", x: 150, y: 310 },
        { id: "인공지능연구원 1", x: 200, y: 290 },
        { id: "LG연구동 1", x: 250, y: 310, },
        { id: "대학본관 1", x: 300, y: 290 },
        { id: "대학본관 2", x: 350, y: 310 },
        { id: "대학본관 3", x: 400, y: 290, },
        { id: "LG연구동 2", x: 250, y: 260 },
        { id: "LG연구동 4", x: 200, y: 190 },
        { id: "LG연구동 3", x: 250, y: 210 },
        { id: "LG연구동 5", x: 300, y: 190 },
        { id: "환경공학동 1", x: 250, y: 160 },
        { id: "환경공학동 3", x: 200, y: 90 },
        { id: "환경공학동 2", x: 250, y: 110, },
        { id: "환경공학동 4", x: 300, y: 90, },
    ],
    links: [
        { source: "RIST 4", target: "RIST 3" },
        { source: "RIST 3", target: "RIST 5" },
        { source: "RIST 3", target: "RIST 4" },
        { source: "RIST 3", target: "RIST 2" },
        { source: "RIST 5", target: "RIST 3" },
        { source: "노벨동산 4", target: "노벨동산 3" },
        { source: "노벨동산 2", target: "노벨동산 1" },
        { source: "RIST 2", target: "RIST 3" },
        { source: "RIST 2", target: "RIST 1" },
        { source: "노벨동산 3", target: "노벨동산 4" },
        { source: "노벨동산 3", target: "인공지능연구원 4" },
        { source: "노벨동산 1", target: "노벨동산 2" },
        { source: "노벨동산 1", target: "인공지능연구원 2" },
        { source: "RIST 1", target: "RIST 2" },
        { source: "RIST 1", target: "LG연구동 1" },
        { source: "대학본관 4", target: "대학본관 3" },
        { source: "인공지능연구원 4", target: "인공지능연구원 3" },
        { source: "인공지능연구원 4", target: "노벨동산 3" },
        { source: "인공지능연구원 3", target: "인공지능연구원 2" },
        { source: "인공지능연구원 3", target: "인공지능연구원 4" },
        { source: "인공지능연구원 2", target: "인공지능연구원 1" },
        { source: "인공지능연구원 2", target: "인공지능연구원 3" },
        { source: "인공지능연구원 2", target: "노벨동산 1" },
        { source: "인공지능연구원 1", target: "LG연구동 1" },
        { source: "인공지능연구원 1", target: "인공지능연구원 2" },
        { source: "LG연구동 1", target: "대학본관 1" },
        { source: "LG연구동 1", target: "인공지능연구원 1" },
        { source: "LG연구동 1", target: "RIST 1" },
        { source: "LG연구동 1", target: "LG연구동 2" },
        { source: "대학본관 1", target: "대학본관 2" },
        { source: "대학본관 1", target: "LG연구동 1" },
        { source: "대학본관 2", target: "대학본관 3" },
        { source: "대학본관 2", target: "대학본관 1" },
        { source: "대학본관 3", target: "대학본관 2" },
        { source: "대학본관 3", target: "대학본관 4" },
        { source: "LG연구동 2", target: "LG연구동 1" },
        { source: "LG연구동 2", target: "LG연구동 3" },
        { source: "LG연구동 4", target: "LG연구동 3" },
        { source: "LG연구동 3", target: "LG연구동 5" },
        { source: "LG연구동 3", target: "LG연구동 4" },
        { source: "LG연구동 3", target: "LG연구동 2" },
        { source: "LG연구동 3", target: "환경공학동 1" },
        { source: "LG연구동 5", target: "LG연구동 3" },
        { source: "환경공학동 1", target: "LG연구동 3" },
        { source: "환경공학동 1", target: "환경공학동 2" },
        { source: "환경공학동 3", target: "환경공학동 2" },
        { source: "환경공학동 2", target: "환경공학동 4" },
        { source: "환경공학동 2", target: "환경공학동 3" },
        { source: "환경공학동 2", target: "환경공학동 1" },
        { source: "환경공학동 4", target: "환경공학동 2" },
    ],
},{
    nodes: [
        { id: "포스플렉스 1", x: 250, y: 460 },
        { id: "포스플렉스 2", x: 300, y: 440, },
        { id: "포스플렉스 3", x: 350, y: 460, },
        { id: "테니스장 3", x: 100, y: 390, },
        { id: "체육관 3", x: 250, y: 410 },
        { id: "테니스장 1", x: 50, y: 360 },
        { id: "테니스장 2", x: 100, y: 340, },
        { id: "체육관 2", x: 250, y: 360 },
        { id: "화학관 2", x: 350, y: 360 },
        { id: "풋살구장 3", x: 50, y: 310 },
        { id: "체육관 1", x: 250, y: 310 },
        { id: "화학관 1", x: 350, y: 310, },
        { id: "풋살구장 2", x: 50, y: 260 },
        { id: "풋살구장 1", x: 100, y: 240, },
        { id: "통나무집 2", x: 150, y: 260 },
        { id: "통나무집 1", x: 200, y: 240 },
        { id: "나노융합기술원 1", x: 250, y: 260, },
        { id: "생명과학관 1", x: 300, y: 240 },
        { id: "생명과학관 2", x: 350, y: 260 },
        { id: "기계실험동 1", x: 400, y: 240 },
        { id: "기계실험동 2", x: 450, y: 260, },
        { id: "통나무집 3", x: 150, y: 210 },
        { id: "나노융합기술원 2", x: 250, y: 210 },
        { id: "나노융합기술원 3", x: 250, y: 160 },
        { id: "나노융합기술원 4", x: 250, y: 110, },
        { id: "포항가속기연구소", x: 250, y: 60 },
    ],
    links: [
        { source: "포스플렉스 1", target: "포스플렉스 2" },
        { source: "포스플렉스 1", target: "체육관 3" },
        { source: "포스플렉스 2", target: "포스플렉스 3" },
        { source: "포스플렉스 2", target: "포스플렉스 1" },
        { source: "포스플렉스 3", target: "포스플렉스 2" },
        { source: "테니스장 3", target: "테니스장 2" },
        { source: "체육관 3", target: "포스플렉스 1" },
        { source: "체육관 3", target: "체육관 2" },
        { source: "테니스장 1", target: "테니스장 2" },
        { source: "테니스장 1", target: "풋살구장 3" },
        { source: "테니스장 2", target: "테니스장 1" },
        { source: "테니스장 2", target: "테니스장 3" },
        { source: "체육관 2", target: "체육관 3" },
        { source: "체육관 2", target: "체육관 1" },
        { source: "화학관 2", target: "화학관 1" },
        { source: "풋살구장 3", target: "테니스장 1" },
        { source: "풋살구장 3", target: "풋살구장 2" },
        { source: "체육관 1", target: "체육관 2" },
        { source: "체육관 1", target: "나노융합기술원 1" },
        { source: "화학관 1", target: "화학관 2" },
        { source: "화학관 1", target: "생명과학관 2" },
        { source: "풋살구장 2", target: "풋살구장 1" },
        { source: "풋살구장 2", target: "풋살구장 3" },
        { source: "풋살구장 1", target: "통나무집 2" },
        { source: "풋살구장 1", target: "풋살구장 2" },
        { source: "통나무집 2", target: "통나무집 1" },
        { source: "통나무집 2", target: "풋살구장 1" },
        { source: "통나무집 2", target: "통나무집 3" },
        { source: "통나무집 1", target: "나노융합기술원 1" },
        { source: "통나무집 1", target: "통나무집 2" },
        { source: "나노융합기술원 1", target: "생명과학관 1" },
        { source: "나노융합기술원 1", target: "통나무집 1" },
        { source: "나노융합기술원 1", target: "체육관 1" },
        { source: "나노융합기술원 1", target: "나노융합기술원 2" },
        { source: "생명과학관 1", target: "생명과학관 2" },
        { source: "생명과학관 1", target: "나노융합기술원 1" },
        { source: "생명과학관 2", target: "기계실험동 1" },
        { source: "생명과학관 2", target: "생명과학관 1" },
        { source: "생명과학관 2", target: "화학관 1" },
        { source: "기계실험동 1", target: "기계실험동 2" },
        { source: "기계실험동 1", target: "생명과학관 2" },
        { source: "기계실험동 2", target: "기계실험동 1" },
        { source: "통나무집 3", target: "통나무집 2" },
        { source: "나노융합기술원 2", target: "나노융합기술원 1" },
        { source: "나노융합기술원 2", target: "나노융합기술원 3" },
        { source: "나노융합기술원 3", target: "나노융합기술원 2" },
        { source: "나노융합기술원 3", target: "나노융합기술원 4" },
        { source: "나노융합기술원 4", target: "나노융합기술원 3" },
        { source: "나노융합기술원 4", target: "포항가속기연구소" },
        { source: "포항가속기연구소", target: "나노융합기술원 4" },
    ],
}
]